[package]
name = "sut_native"
version = "0.1.0"
edition = "2021"

[dependencies]
rustler = { version = "0.34.0", features = ["nif_version_2_17"] }
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread"] }
